# fly.toml app configuration file generated for catapio-home on 2025-03-09T22:08:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'catapio-home'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = "1gb"

[env]
  EMAIL_USER = "noreply@catap.io"
  EMAIL_TO = "contact@catap.io"
  EMAIL_HOST = "smtp.zoho.com"
  EMAIL_PORT = "465"
  EMAIL_SECURE = "true"
